language: node_js

node_js:
  - "8"

branches:
  only:
    - master

# services: 
#   - postgresql

# env:
#   - TEST_DB_NAME=<test_db_name> DB_PORT=5432 DB_NAME=<main_db_name>

# before_script:
#   - psql -c 'create database <test_db_name>;' -U postgres

script: npm install && npm test; cd client && npm run cy:run